all : native-code
RESULT = gueb 
SOURCES = program_piqi.ml absenvgenerique.ml absenv.ml ir.ml reil.ml stubfunc.ml uafgenerique.ml uafastree.ml uafgroupbyfree.ml uafgroupbyalloc.ml graph.ml gueb.ml 
PACKS =  piqirun.ext piqilib unix
OCAMLFLAGS = -w A  -warn-error A 

-include OCamlMakefile  
